spring:
  application:
    name: flappybird_backend
  datasource:
    # mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/flappy_bird?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
springdoc:
  api-docs:
    enabled: true
knife4j:
  setting:
    language: zh_cn